# This file was generated by GoReleaser. DO NOT EDIT.
cask "bb" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "{{staged_path}}/bb"]
    end
  end

  version "0.6.2"

  on_macos do
    on_arm do
      sha256 "1a4b63cd1517f85872d48a29e141e80d7c92c7428268887c810d5dca7af62c19"
      url "https://github.com/avitsrimer/bitbucket-cli/releases/download/v#{version}/bb_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "bb"
  desc "Command-line interface to manage Bitbucket pull requests, profiles, and users"
  homepage "https://github.com/avitsrimer/bitbucket-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bb"

  # No zap stanza required
end
