# This file was generated by GoReleaser. DO NOT EDIT.
cask "bb" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "f7853859fe2017ec328a7f8458c1463b133e3906e690aa520f9c0550e90a1025"
      url "https://github.com/avitsrimer/bitbucket-cli/releases/download/v#{version}/bb_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "bb"
  desc "Command-line interface to manage Bitbucket pull requests, profiles, and users"
  homepage "https://github.com/avitsrimer/bitbucket-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bb"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bb"]
    end
  end

  # No zap stanza required
end
