# This file was generated by GoReleaser. DO NOT EDIT.
cask "bb" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "5240a1dbf2a5d78184237c4b3e5fdadcd1a8bde376282d6a0f83d3574ac536ad"
      url "https://github.com/avitsrimer/bitbucket-cli/releases/download/v#{version}/bb_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "bb"
  desc "Command-line interface to manage Bitbucket pull requests, profiles, and users"
  homepage "https://github.com/avitsrimer/bitbucket-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bb"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bb"]
    end
  end

  # No zap stanza required

end
