# This file was generated by GoReleaser. DO NOT EDIT.
cask "bitbucket-cli" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "{{staged_path}}/bb"]
    end
  end

  version "0.6.3"

  on_macos do
    on_arm do
      sha256 "279ef7d70a0d2193f7668c2af7688c53676e33c021e3b305fae0fb0864fd212b"
      url "https://github.com/avitsrimer/bitbucket-cli/releases/download/v#{version}/bb_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "bitbucket-cli"
  desc "Command-line interface to manage Bitbucket pull requests, profiles, and users"
  homepage "https://github.com/avitsrimer/bitbucket-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bb"

  # No zap stanza required
end
