# This file was generated by GoReleaser. DO NOT EDIT.
cask "grafanapi" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "c702bd51bcf52023f9599dbb107d3a06c350c6ba734a03a2771ab22dc3c84446"
      url "https://github.com/avitsrimer/grafanapi/releases/download/v#{version}/grafanapi_Darwin_arm64.tar.gz"
    end
  end

  name "grafanapi"
  desc "grafanapi: a session-cookie-authenticated CLI for managing Grafana resources"
  homepage "https://github.com/avitsrimer/grafanapi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grafanapi"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grafanapi"]
    end
  end

  # No zap stanza required

end
