# This file was generated by GoReleaser. DO NOT EDIT.
cask "grafanapi" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "bff2fd9969fd3c1a21d791569901ff920e522513f6215bcd0ff77cff1ab3d995"
      url "https://github.com/avitsrimer/grafanapi/releases/download/v#{version}/grafanapi_Darwin_arm64.tar.gz"
    end
  end

  name "grafanapi"
  desc "grafanapi: a session-cookie-authenticated CLI for managing Grafana resources"
  homepage "https://github.com/avitsrimer/grafanapi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grafanapi"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grafanapi"]
    end
  end

  # No zap stanza required

end
