# This file was generated by GoReleaser. DO NOT EDIT.
cask "grafanapi" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "{{staged_path}}/grafanapi"]
    end
  end

  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "7e5bad7934c8d1cbfd29d93c0224479a235527f365926b2e9cf12284f7b29237"
      url "https://github.com/avitsrimer/grafanapi/releases/download/v#{version}/grafanapi_Darwin_arm64.tar.gz"
    end
  end

  name "grafanapi"
  desc "grafanapi: a session-cookie-authenticated CLI for managing Grafana resources"
  homepage "https://github.com/avitsrimer/grafanapi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grafanapi"

  # No zap stanza required
end
