# This file was generated by GoReleaser. DO NOT EDIT.
cask "jcli" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "2bcbcfaeb11c9847ba77e81fa5806868c3f52ed355285f2f127a5bb54941197a"
      url "https://github.com/avitsrimer/jcli/releases/download/v#{version}/jcli_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "jcli"
  desc "General-purpose macOS Jenkins CLI with Keychain-backed credentials"
  homepage "https://github.com/avitsrimer/jcli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jcli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jcli"]
    end
  end

  # No zap stanza required

end
