# This file was generated by GoReleaser. DO NOT EDIT.
cask "jcli" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "be7ed7682f391db262781ca6c2dd3b0b1360f0a60968d8058252ce689a8888c7"
      url "https://github.com/avitsrimer/jcli/releases/download/v#{version}/jcli_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "jcli"
  desc "General-purpose macOS Jenkins CLI with Keychain-backed credentials"
  homepage "https://github.com/avitsrimer/jcli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jcli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jcli"]
    end
  end

  # No zap stanza required

end
